version: "3.9"
services:
    nextjs:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - ./prisma/dev.db:/app/prisma/dev.db
        environment:
            - NODE_ENV=production
        ports:
            - "9005:3000"
